#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Sep 19, 2019 09:53:14 AM CEST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 958x1008+-7+0
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "YouTubeCommenter"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra51 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 175 -highlightbackground #f0f0f0 -highlightcolor black \
        -width 945 
    vTcl:DefineAlias "$top.fra51" "Info Frame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra51
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Year 
    vTcl:DefineAlias "$site_3_0.lab52" "Label_year" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Month 
    vTcl:DefineAlias "$site_3_0.lab53" "Label_month" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text keyWord 
    vTcl:DefineAlias "$site_3_0.lab54" "Label_keyword" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex56 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 114 -wrap word 
    .top42.fra51.tex56 configure -font "TkTextFont"
    .top42.fra51.tex56 insert end text
    vTcl:DefineAlias "$site_3_0.tex56" "text_year" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex57 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 114 -wrap word 
    .top42.fra51.tex57 configure -font "TkTextFont"
    .top42.fra51.tex57 insert end text
    vTcl:DefineAlias "$site_3_0.tex57" "text_month" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex58 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 324 -wrap word 
    .top42.fra51.tex58 configure -font "TkTextFont"
    .top42.fra51.tex58 insert end text
    vTcl:DefineAlias "$site_3_0.tex58" "text_keyword" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Comment 
    vTcl:DefineAlias "$site_3_0.lab59" "Label_comment" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex60 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 294 -wrap word 
    .top42.fra51.tex60 configure -font "TkTextFont"
    .top42.fra51.tex60 insert end text
    vTcl:DefineAlias "$site_3_0.tex60" "text_comment" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Start Comment} 
    vTcl:DefineAlias "$site_3_0.but67" "Button_startComment" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab52 \
        -in $site_3_0 -x 40 -y 20 -width 64 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 220 -y 20 -width 84 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 420 -y 20 -width 105 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex56 \
        -in $site_3_0 -x 110 -y 25 -width 100 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex57 \
        -in $site_3_0 -x 305 -y 25 -width 100 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex58 \
        -in $site_3_0 -x 530 -y 25 -width 300 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 20 -y 50 -width 84 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex60 \
        -in $site_3_0 -x 110 -y 60 -width 294 -relwidth 0 -height 104 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but67 \
        -in $site_3_0 -x 540 -y 110 -width 242 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra69 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 195 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 745 
    vTcl:DefineAlias "$top.fra69" "Authentication Frame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra69
    button $site_3_0.but70 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Create Conniction with Google Account} 
    vTcl:DefineAlias "$site_3_0.but70" "Button_createConnection" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {insert the return code from Google Auth here} 
    vTcl:DefineAlias "$site_3_0.lab71" "Label_codeInfo" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex72 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 564 -wrap word 
    .top42.fra69.tex72 configure -font "TkTextFont"
    .top42.fra69.tex72 insert end text
    vTcl:DefineAlias "$site_3_0.tex72" "Text_code" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but73 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Submit the Code} 
    vTcl:DefineAlias "$site_3_0.but73" "Button_submetCode" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex43 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 434 -wrap word 
    .top42.fra69.tex43 configure -font "TkTextFont"
    .top42.fra69.tex43 insert end text
    vTcl:DefineAlias "$site_3_0.tex43" "Text_LinkAuth" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but70 \
        -in $site_3_0 -x 10 -y 20 -width 277 -relwidth 0 -height 104 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 10 -y 140 -width 244 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex72 \
        -in $site_3_0 -x 10 -y 160 -width 564 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but73 \
        -in $site_3_0 -x 580 -y 160 -width 143 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex43 \
        -in $site_3_0 -x 290 -y 20 -width 434 -relwidth 0 -height 104 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra75 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 275 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 945 
    vTcl:DefineAlias "$top.fra75" "Output Frame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra75
    listbox $site_3_0.lis76 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 232 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -width 924 
    .top42.fra75.lis76 configure -font "TkFixedFont"
    .top42.fra75.lis76 insert end text
    vTcl:DefineAlias "$site_3_0.lis76" "OutputList" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab77 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Outbuts Lists} 
    vTcl:DefineAlias "$site_3_0.lab77" "Label_outputList" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lis76 \
        -in $site_3_0 -x -40 -y 60 -width 924 -relwidth 0 -height 232 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 10 -y 10 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra51 \
        -in $top -x 10 -y 230 -width 945 -relwidth 0 -height 175 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra69 \
        -in $top -x 120 -y 10 -width 745 -relwidth 0 -height 195 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra75 \
        -in $top -x 10 -y 430 -width 945 -relwidth 0 -height 275 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

